#!/usr/bin/env bash

# Display project information

echo "📚 School Ecosystem Project Information"
echo ""
echo "Project: Ekosistem Sekolah SaaS Platform"
echo "Description: School management system with federated identity"
echo ""
echo "Tech Stack:"
echo "  - Next.js 14"
echo "  - Turborepo (Monorepo)"
echo "  - PNPM (Package Manager)"
echo "  - TypeScript"
echo "  - Supabase (Database)"
echo ""
echo "Workspace Packages:"
pnpm list --depth 0 | grep "@repo/" || echo "  (Run 'pnpm install' first)"
echo ""
echo "Useful commands:"
echo "  pnpm dev           - Start development"
echo "  pnpm build         - Build all packages"
echo "  pnpm type-check    - Check TypeScript"
echo "  pnpm lint          - Lint code"
echo "  pnpm test          - Run tests"
echo ""
echo "Scripts:"
echo "  ./scripts/setup.sh              - Initial setup"
echo "  ./scripts/dev/clean.sh          - Clean artifacts"
echo "  ./scripts/dev/reset.sh          - Reset project"
echo "  ./scripts/dev/check-all.sh      - Run all checks"
echo "  ./scripts/test/run-all.sh       - Run all tests"
echo "  ./scripts/build/all.sh          - Build everything"
echo ""
